import { NavItem, HeaderNavItem, User, Task, Email, DriveItem, Folder, FileObject } from './types';

export enum Page {
  Home = 'Home',
  Inbox = 'Inbox',
  Tasks = 'Tasks',
  Drive = 'Drive',
  Templates = 'Templates',
  HRM = 'HRM',
  Flagged = 'Flagged',
  Sent = 'Sent',
  Drafts = 'Drafts',
  Archive = 'Archive',
  Trash = 'Trash',
  Notifications = 'Notifications',
  Favorites = 'Favorites',
  People = 'People',
  TimeAttendance = 'Time & Attendance',
  LeaveVacations = 'Leave & Vacations',
  Pay = 'Pay',
  Assets = 'Assets',
  Performance = 'Performance',
  Reports = 'Reports',
  OrganizationProfile = 'Organization Profile',
  MyAccount = 'My Account',
  HumanResources = 'Human Resources',
  FinanceAccounting = 'Finance & Accounting',
  SalesMarketing = 'Sales & Marketing',
  ProductOperations = 'Product & Operations',
  LegalAgreements = 'Legal Agreements',
  Administration = 'Administration',
  BusinessPlan = 'Business Plan',
  StartBusiness = 'Start a Business',
  FreeTemplates = 'Free Templates',
  RecentlyAdded = 'Recently Added',
  Top50 = 'Top 50 Templates',
  DocumentTypes = 'Document Types',
  BusinessIndustries = 'Business Industries',
  DocumentGenerator = 'Document Generator',
  Certificates = 'Certificates',
  // FIX: Add missing Page enum members for TasksPage
  Projects = 'Projects',
  Goals = 'Goals',
  Chart = 'Chart',
}

export enum IconName {
    Home = 'Home',
    Inbox = 'Inbox',
    Flag = 'Flag',
    Send = 'Send',
    Draft = 'Draft',
    Archive = 'Archive',
    Trash = 'Trash',
    Bell = 'Bell',
    Star = 'Star',
    CheckCircle = 'CheckCircle',
    Folder = 'Folder',
    Tasks = 'Tasks',
    Projects = 'Projects',
    Goals = 'Goals',
    Chart = 'Chart',
    Users = 'Users',
    UserCircle = 'UserCircle',
    Clock = 'Clock',
    Calendar = 'Calendar',
    Briefcase = 'Briefcase',
    CreditCard = 'CreditCard',
    ShieldCheck = 'ShieldCheck',
    ClipboardList = 'ClipboardList',
    TrendingUp = 'TrendingUp',
    Building = 'Building',
    FileText = 'FileText',
    Rocket = 'Rocket',
    Gift = 'Gift',
    ClockRewind = 'ClockRewind',
    Award = 'Award',

    Filter = 'Filter',
    Group = 'Group',
    Sort = 'Sort',
    Plus = 'Plus',
    ChevronDown = 'ChevronDown',
    ChevronRight = 'ChevronRight',
    Search = 'Search',
    CloudUpload = 'CloudUpload',
    FilePlus = 'FilePlus',
    FolderPlus = 'FolderPlus',
    Grid = 'Grid',
    List = 'List',
    ChevronLeft = 'ChevronLeft',
    Microphone = 'Microphone',
    StopCircle = 'StopCircle',
    X = 'X',
    Sparkles = 'Sparkles',
    MessageSquare = 'MessageSquare',
    Link = 'Link',
    Paperclip = 'Paperclip',
    BookOpen = 'BookOpen',
    Sheet = 'Sheet',
    Edit = 'Edit',
    Users2 = 'Users2',
    Phone = 'Phone',
    Hrm = 'Hrm',
    Ai = 'Ai',

    // FIX: Add missing IconName enum members
    Drive = 'Drive',
    Templates = 'Templates',
    QuestionMarkCircle = 'QuestionMarkCircle',
    HumanResources = 'HumanResources',
    FinanceAccounting = 'FinanceAccounting',
    SalesMarketing = 'SalesMarketing',
    ProductOperations = 'ProductOperations',
    LegalAgreements = 'LegalAgreements',
    Administration = 'Administration',
    BusinessPlan = 'BusinessPlan',
    StartBusiness = 'StartBusiness',
    FreeTemplates = 'FreeTemplates',
    RecentlyAdded = 'RecentlyAdded',
    Top50 = 'Top50',
    DocumentTypes = 'DocumentTypes',
    BusinessIndustries = 'BusinessIndustries',
    Favorites = 'Favorites',
}

export const sidebarNavItems: NavItem[] = [
  { icon: IconName.Home, label: 'Home', page: Page.Home },
  { icon: IconName.Inbox, label: 'Inbox', page: Page.Inbox },
  { icon: IconName.Tasks, label: 'Tasks', page: Page.Tasks },
  { icon: IconName.Drive, label: 'Drive', page: Page.Drive },
  { icon: IconName.Templates, label: 'Templates', page: Page.Templates },
  // FIX: Changed IconName.HRM to IconName.Hrm to match enum definition
  { icon: IconName.Hrm, label: 'HRM', page: Page.HRM },
  { icon: IconName.FileText, label: 'Docs', page: Page.DocumentGenerator },
  { icon: IconName.ShieldCheck, label: 'Certificates', page: Page.Certificates },
  { icon: IconName.Flag, label: 'Flagged', page: Page.Flagged },
  { icon: IconName.Send, label: 'Sent', page: Page.Sent },
  { icon: IconName.Draft, label: 'Drafts', page: Page.Drafts },
];

export const headerNavItems: HeaderNavItem[] = [
    { label: 'BIB Cont...', page: Page.Home },
    { label: 'BIB Links', page: Page.Home },
    { label: 'BIB Notes', page: Page.Home },
    { label: 'BIB Sheet...', page: Page.Home },
    { label: 'BIB Docs...', page: Page.Home },
    { label: 'BIB Temp...', page: Page.Home },
    { label: 'BIB Cloud...', page: Page.Home },
    { label: 'BIB Conn...', page: Page.Home },
    { label: 'BIB Chat', page: Page.Home },
    { label: 'BIB Tasks...', page: Page.Tasks },
    { label: 'BIB Home', page: Page.Home },
];

export const user: User = {
  name: 'Mohamed Efadil',
  initials: 'ME',
};

export const mockTasks: Task[] = [
    { id: 1, name: "Finalize Q3 marketing report", priority: "High", status: "In Progress" },
    { id: 2, name: "Develop prototype for Project Phoenix", priority: "High", status: "Todo" },
    { id: 3, name: "Schedule team offsite for September", priority: "Medium", status: "Todo" },
    { id: 4, name: "Update client contact database", priority: "Low", status: "Done" },
    { id: 5, name: "Review and approve expense reports", priority: "Medium", status: "In Progress" },
    { id: 6, name: "Onboard new software engineer", priority: "High", status: "Todo" },
];

export const mockEmails: Email[] = [
    { id: 1, from: "Alice Johnson", subject: "Re: Q3 Marketing Report", body: "Here is the draft of the Q3 marketing report for your review. Please provide feedback by EOD tomorrow.", timestamp: "2 hours ago", folder: "Inbox" },
    { id: 2, from: "Bob Williams", subject: "Project Phoenix Update", body: "The initial prototype design is complete. Let's schedule a meeting to discuss next steps.", timestamp: "5 hours ago", folder: "Inbox" },
    { id: 3, from: "HR Department", subject: "Action Required: Annual Training", body: "Please complete the mandatory annual security training by the end of the month.", timestamp: "1 day ago", folder: "Inbox" },
    { id: 4, to: "Alice Johnson", subject: "Re: Q3 Marketing Report", body: "Thanks, Alice. I'll review it this afternoon.", timestamp: "1 hour ago", folder: "Sent" },
    { id: 5, to: "All Staff", subject: "Draft: Company Offsite Announcement", body: "...", timestamp: "3 days ago", folder: "Drafts" },
];

export const mockFolders: Folder[] = [
    { id: 1, name: "Administration", type: 'folder' },
    { id: 2, name: "Finance", type: 'folder' },
    { id: 3, name: "Human Resources", type: 'folder' },
    { id: 4, name: "Legal", type: 'folder' },
    { id: 5, name: "Marketing", type: 'folder' },
    { id: 6, name: "Operations", type: 'folder' },
    { id: 7, name: "Products", type: 'folder' },
    { id: 8, name: "Sales", type: 'folder' },
    { id: 9, name: "Service", type: 'folder' },
    { id: 10, name: "Technology", type: 'folder' },
];

export const mockFiles: FileObject[] = [
    { id: 11, name: "Q3_Marketing_Report_Draft.docx", type: 'file', size: '1.2 MB' },
    { id: 12, name: "Project_Phoenix_Brief.pdf", type: 'file', size: '800 KB' },
    { id: 13, name: "2025_Budget.xlsx", type: 'file', size: '450 KB' },
];

export const mockEmployees = [
    { name: 'Mohamed Efadil Abuagla', status: 'Offline', in: '--', out: '--', breaks: '00:00', total: '--' },
    { name: 'Jane Doe', status: 'Online', in: '09:01', out: '--', breaks: '00:15', total: '04:44' },
    { name: 'John Smith', status: 'On Leave', in: '--', out: '--', breaks: '--', total: '--' },
];
